version: '3'

services:
    zookeeper:
        container_name: zookeeper
        hostname: zookeeper
        image: zookeeper
        ports:
            - "2181:2181"
      
    kafka:
        container_name: kafka
        hostname: kafka
        image: wurstmeister/kafka:2.12-2.3.0
        ports:
            - "9092:9092"
        depends_on:
            - zookeeper
        environment:
            KAFKA_ADVERTISED_HOST_NAME: kafka
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_PORT: 9092
            KAFKA_CREATE_TOPICS: "flight_delay_classification_request:1:1"

    mongo:
        container_name: mongo
        hostname: mongo
        image: mongo:latest
        ports:
            - "27017:27017"
        depends_on: 
            - kafka
        volumes:
            - ./practica_big_data_2019:/home
            
    mongo-import:
        container_name: mongo-import
        hostname: mongo-import
        image: mongo:latest
        depends_on:
            - mongo
        volumes:
            - ./practica_big_data_2019:/home
        command: ./home/resources/import_distances.sh
          
    master:
        container_name: master
        hostname: master
        image: bde2020/spark-master:2.4.4-hadoop2.7
        environment:
            - INIT_DAEMON_STEP=setup_spark
        ports:
            - "7077:7077"
            - "8080:8080"
        depends_on:
            - kafka
            - mongo
        volumes:
            - ./practica_big_data_2019:/home

    worker:
        container_name: worker
        hostname: worker
        image: bde2020/spark-master:2.4.4-hadoop2.7
        command: spark/bin/spark-submit --class es.upm.dit.ging.predictor.MakePrediction --master spark://master:7077 --packages org.mongodb.spark:mongo-spark-connector_2.11:2.4.0,org.apache.spark:spark-sql-kafka-0-10_2.11:2.4.0 /home/flight_prediction/target/scala-2.11/flight_prediction_2.11-0.1.jar &
        environment:
            - "SPARK_MASTER=spark://master:7077"
        ports:
            - "8081:8081"
        depends_on:
            - master
            - kafka
            - mongo
        volumes:
            - ./practica_big_data_2019:/home

    flask:
        container_name: flask
        hostname: flask
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
            - "9200:9200"
        depends_on:
            - master
            - worker
            - mongo
        environment:
            PROJECT_HOME: /home
        volumes:
            - ./practica_big_data_2019:/home
        command: python3 /home/resources/web/predict_flask.py